version: "3"
services:
  test-db:
    image: mysql:5.7
    container_name: test-db
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
      - .:/broadpackager-test
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: root
      MYSQL_ROOT_HOST: localhost
  web:
    build: .
    container_name: broadpackager-test
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/broadpackager-test
      - web_rubygems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - test-db
    tty: true
    stdin_open: true
volumes:
  db_data:
  web_rubygems:
